services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/neo4j123
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always